version: "3.8"
services:
  cz:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./src:/app/src # do not replace node_modules
    ports:
      - "5173:5173"
    tty: true
